---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", {ip: "10.8.9.10"}]

provisioner:
  name: chef_solo
  attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - recipe[balanced-docker]
